### ISSUE TITLE
Progress? ETA?

### ISSUE THREAD

**Issue by ffMathy** [OrleansContrib/Orleans.Providers.RabbitMQ#4]
Is this provider still being developed? Are there any plans for the future? What's the status?

**Comment by creyke** [comment]
No plans for further development. I will update the readme to reflect.

**Comment by ffMathy** [comment]
@creyke that's all good (and thanks for the swift reply), but is it because there is a better implementation out there? Does one exist?

**Comment by creyke** [comment]
There are others around but I am unaware how active they are / whether they are being used in highly available / high scale production environments. I recommend asking in https://gitter.im/dotnet/orleans
